# taking golang from docker library
FROM golang:1.22.1

# META DATA 
LABEL version="1.0" maintainer="imazlin"

# COPY NEEDED FILES
COPY container /

# work repertory
WORKDIR /lem-in

# LAUNCH PORT
EXPOSE 2030
